import './style.css';
const $=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d');
const W=1000,H=800,GATE_X=850,BALL_R=18,TOP=150,BOTTOM=650;
let phase='ready',audioOn=false,audio,state,best=null;
try{const n=Number(localStorage.getItem('polaridad-best'));if(Number.isFinite(n)&&n>=0)best=n}catch{}
const rand=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function simulate(y0,vy0,vx,a,sign,tapT,totalT){let y=y0,vy=vy0,t=0,dt=.008,s=sign;while(t<totalT){if(t<tapT&&t+dt>=tapT)s*=-1;vy+=a*s*dt;y+=vy*dt;t+=dt;if(y<TOP+BALL_R||y>BOTTOM-BALL_R)return null}return y}
function makeSolvable(){for(let tries=0;tries<80;tries++){const vx=rand(175,205),totalT=(GATE_X-95)/vx,a=rand(88,118),sign=Math.random()<.5?-1:1,y0=rand(350,450),vy0=rand(-18,18),ideal=rand(.9,Math.max(1.15,totalT-1.15)),gateY=simulate(y0,vy0,vx,a,sign,ideal,totalT);if(gateY&&gateY>255&&gateY<545)return{vx,totalT,a,sign,y0,vy0,ideal,gateY}}return{vx:190,totalT:3.97,a:100,sign:-1,y0:410,vy0:0,ideal:1.9,gateY:405}}
function newRound(){const s=makeSolvable();state={...s,last:performance.now(),x:95,y:s.y0,vy:s.vy0,t:0,switched:false,trail:[],hit:false,resultAt:0,flash:0};phase='ready';$('ready').hidden=false;$('result').hidden=true;$('action').disabled=false;$('action').querySelector('span').textContent='INVERTIR POLARIDAD';$('scene-label').textContent='TOCA CUANDO QUIERAS CAMBIAR LA CURVA';$('best').textContent=best===null?'MEJOR · —':'MEJOR · '+Math.round(best)+' PX'}
function tone(f=360,d=.12){if(!audioOn)return;try{audio??=new AudioContext();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;g.gain.setValueAtTime(.055,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d+.02)}catch{}}
function switchPolarity(){if(phase!=='ready'||state.switched)return;state.switched=true;state.sign*=-1;state.flash=1;$('action').disabled=true;$('action').querySelector('span').textContent='POLARIDAD INVERTIDA';$('scene-label').textContent='INVERTIDA · AHORA SOLO MIRA…';tone(280,.08)}
function end(success,impactY){if(phase==='result')return;phase='result';state.resultAt=performance.now();const miss=Math.abs(impactY-state.gateY);let verdict,detail;if(success){verdict=miss<=18?'¡Perfecto!':'¡Dentro!';detail=miss<=18?'Pasaste prácticamente por el centro.':'Entraste limpio. Te faltaron '+Math.round(miss)+' px para el centro.';if(best===null||miss<best){best=miss;try{localStorage.setItem('polaridad-best',String(best))}catch{}}confetti();tone(miss<=18?760:560,.18)}else{verdict='Rozaste.';detail=impactY<state.gateY?'Te fuiste demasiado arriba.':'Te fuiste demasiado abajo.';tone(130,.2)}$('verdict').textContent=verdict;$('distance').textContent=Math.round(miss);$('detail').textContent=detail;$('best').textContent=best===null?'MEJOR · —':'MEJOR · '+Math.round(best)+' PX';$('ready').hidden=true;$('result').hidden=false;$('scene-label').textContent=success?verdict.toUpperCase()+' · '+Math.round(miss)+' PX DEL CENTRO':'IMPACTO · '+verdict.toUpperCase();try{window.goatcounter?.count?.({path:'polaridad-completada',title:'Polaridad completada',event:true,no_session:true})}catch{}}
function confetti(){const host=$('scene');for(let i=0;i<26;i++){const e=document.createElement('i');e.className='confetti';e.style.left=(74+Math.random()*10)+'%';e.style.top=(38+Math.random()*18)+'%';e.style.setProperty('--dx',((Math.random()-.5)*280)+'px');e.style.setProperty('--dy',(90+Math.random()*220)+'px');host.appendChild(e);setTimeout(()=>e.remove(),1200)}}
function rounded(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.stroke()}}
function pole(y,h,label,color){ctx.save();rounded(115,y,650,h,24,color,'#26302b');ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#f4efe5';ctx.font='700 34px DM Sans';ctx.textAlign='center';ctx.textBaseline='middle';for(let x=180;x<730;x+=110)ctx.fillText(label,x,y+h/2+1);ctx.restore()}
function drawField(){const up=state.sign<0,topLabel=up?'−':'+',bottomLabel=up?'+':'−',topColor=up?'#315f7a':'#b85347',bottomColor=up?'#b85347':'#315f7a';pole(72,74,topLabel,topColor);pole(654,74,bottomLabel,bottomColor);ctx.save();ctx.strokeStyle='rgba(75,90,82,.15)';ctx.lineWidth=2;for(let y=205;y<620;y+=70){ctx.beginPath();ctx.moveTo(160,y);ctx.bezierCurveTo(360,y+(up?-28:28),570,y+(up?-28:28),760,y);ctx.stroke()}ctx.restore();ctx.fillStyle='#59645d';ctx.font='700 12px DM Sans';ctx.textAlign='center';ctx.fillText(up?'CAMPO ↑':'CAMPO ↓',500,118)}
function drawGate(){const gap=150,gy=state.gateY;ctx.fillStyle='#343b37';ctx.fillRect(GATE_X,TOP,58,gy-gap/2-TOP);ctx.fillRect(GATE_X,gy+gap/2,58,BOTTOM-(gy+gap/2));ctx.fillStyle='#f2b544';ctx.fillRect(GATE_X-8,gy-gap/2,8,gap);ctx.strokeStyle='rgba(242,181,68,.45)';ctx.lineWidth=2;ctx.setLineDash([8,10]);ctx.beginPath();ctx.moveTo(GATE_X-120,gy);ctx.lineTo(GATE_X+45,gy);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#6d756e';ctx.font='700 11px DM Sans';ctx.textAlign='center';ctx.fillText('HUECO',GATE_X+29,gy-94)}
function drawBall(){ctx.save();for(let i=0;i<state.trail.length;i++){const p=state.trail[i],a=(i+1)/state.trail.length*.22;ctx.fillStyle='rgba(65,74,69,'+a+')';ctx.beginPath();ctx.arc(p.x,p.y,5,0,Math.PI*2);ctx.fill()}ctx.shadowColor='rgba(20,24,22,.25)';ctx.shadowBlur=16;ctx.fillStyle='#d8d9d5';ctx.strokeStyle='#59615c';ctx.lineWidth=5;ctx.beginPath();ctx.arc(state.x,state.y,BALL_R,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(state.x-6,state.y-7,5,0,Math.PI*2);ctx.fill();ctx.restore()}
function draw(now){ctx.clearRect(0,0,W,H);ctx.fillStyle='#e8e4da';ctx.fillRect(0,0,W,H);ctx.fillStyle='#efede6';ctx.fillRect(80,142,840,520);ctx.strokeStyle='#c9c8bd';ctx.lineWidth=2;ctx.strokeRect(80,142,840,520);drawField();drawGate();const dt=Math.min(.028,(now-state.last)/1000);state.last=now;if(phase==='ready'){state.t+=dt;state.vy+=state.a*state.sign*dt;state.x+=state.vx*dt;state.y+=state.vy*dt;state.trail.push({x:state.x,y:state.y});if(state.trail.length>24)state.trail.shift();if(state.y<TOP+BALL_R||state.y>BOTTOM-BALL_R){state.y=clamp(state.y,TOP+BALL_R,BOTTOM-BALL_R);end(false,state.y)}else if(state.x+BALL_R>=GATE_X){const gapHalf=75,inside=state.y-BALL_R>state.gateY-gapHalf&&state.y+BALL_R<state.gateY+gapHalf;state.x=GATE_X-BALL_R;end(inside,state.y)}}if(state.flash>0){state.flash=Math.max(0,state.flash-dt*4);ctx.fillStyle='rgba(242,181,68,'+(state.flash*.16)+')';ctx.fillRect(0,0,W,H)}drawBall();requestAnimationFrame(draw)}
$('action').onclick=e=>{e.stopPropagation();switchPolarity()};$('scene').onclick=switchPolarity;$('again').onclick=newRound;document.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&phase==='ready'){e.preventDefault();switchPolarity()}});$('sound').onclick=()=>{audioOn=!audioOn;$('sound').setAttribute('aria-pressed',String(audioOn));$('sound-label').textContent=audioOn?'ON':'OFF';$('sound-icon').textContent=audioOn?'◖))':'◖̸'};$('bookmark').onclick=()=>{$('bookmark-text').textContent=/iPhone|iPad/i.test(navigator.userAgent)?'En Safari, pulsa Compartir y elige «Añadir a favoritos».':'Pulsa Ctrl+D (Windows/Linux), ⌘+D (Mac) o usa el menú del navegador para guardar el juego.';$('bookmark-dialog').showModal()};
newRound();requestAnimationFrame(draw);